- requisitos-project/docs/Guia/Mkdocs.md
- requisitos-project/mkdocs.yml
> Guia do mkdocs

- docs/Planejamento/ferramentas.md
Correções para a entrega 1
- Criação de legenda
> add legenda da tabela

- docs/Planejamento/aplicativo_escolhido.md
- docs/Planejamento/ferramentas.md
Correções para a entrega 1
- Criação de legenda
> add legenda rich picture

- docs/Planejamento/ferramentas.md
- Ajuste do artefato de acordo com o feedback recebido
> Ajuste do artefato de acordo com o feedback recebido

- mkdocs.yml
Havia um erro no endereçamento da página de Apps analisados, mas foi corrigido.
> fix: Corrigindo a Git Pages de Apps Analisados

- docs/Apresentações/apresentacao 01.md
- docs/Atas/Reuniao01.md
- docs/Atas/Reuniao02.md
- docs/Atas/Reuniao03.md
Realização do arquivo apresentações.md para armazenar o vídeo da primeira entrega, e os ajustes das atas de reunião de acordo com o novo template estabelecido
> Alteracoes paulo

- docs/Guia/AdicionandoIcones.md
- docs/index.md
- Correção semântica e gramatical dos textos da aba de guia, no tópico de Ícones Personalizados.
> Correcão da aba de Guias

- docs/Planejamento/ferramentas.md
> correcao de link

- docs/Elicitação/perfil_usuario
Add infos do perfil do usuario.
> perfil do usuario

- docs/Planejamento/cronograma.md
- Correções da entrega 1 + atualizações da entrega 2
> Revisao do  cronograma

- docs/Elicitação/priorizacaoInOrOut.md
- Criação do artefato de priorização in or out
> Create priorizacao In or Out

- docs/Elicitação/priorizacaoInOrOut.md
> Adição de novos requisitos

- docs/Elicitacao/introspeccao.md
- docs/Elicitacao/storytelling.md
Foi realizado o storytelling da elicitação de requisitos
> Entrega2 storytelling

- docs/Elicitacao/personas.md
- docs/Elicitacao/questionario.md
- Pequenas correções de texto em alguns documentos
> refactor: Correção de textos

- docs/Elicitacao/priorizacaoInOrOut.md
Adição da entrevista feita para a priorização in or out e inserção das respostas na tabela
- A tabela foi editada para simplificar a formatação.
- Foram inseridas as informações elicitadas com o cliente.
- O vídeo da entrevista foi incorporado ao documento.
> In or Out: Adição do vídeo e respostas na tabela

- docs/Elicitacao/priorizacao-FTF.md
- Adicionando link do vídeo de priorização FTF. 
- Coautora: @raqueleucaria
> Melhoria entrega 2

- docs/Elicitacao/priorizacaoInOrOut.md
- Padronização de identificadores.
> Melhorias in or out

- README.md
- docs/index.md
> Arrumando index e readme

- docs/Modelagem/cenarios.md
- Criação do artefato de cenários
- [ x] O PR está vinculado a apenas um assunto.
- [ x] O título está objetivo.
- [ x] A descrição está gramaticalmente correta.
- [ x] A branch está direcionada para a main.
- [ x] O revisor foi selecionado corretamente.
> criando cenário

- docs/Modelagem/lexicos.md
> Criando os léxicos

- docs/Modelagem/cenarios.md
- Coloquei legendas nos cenários
> ajustando cenários

- docs/Modelagem/lexicos.md
> Ajustando de style

- docs/Modelagem/especificacao_suplementar.md
- mkdocs.yml
- Documento Referente a Especificação Suplementar
> Especificação Suplementar

- docs/Apresentacoes/apresentacoes.md
- docs/Planejamento/cronograma_realizado.md
- Atualização do cronograma realizado
- Adição do video da Entrega 3
> Atualizacoes para a Entrega 3

- docs/Modelagem/cenarios.md
- Atualizei os cenários
- [x ] O PR está vinculado a apenas um assunto.
- [x ] O título está objetivo.
- [x ] A descrição está gramaticalmente correta.
- [x ] A branch está direcionada para a main.
- [x ] O revisor foi selecionado corretamente.
> atualizando cenários

- docs/Modelagem/cenarios.md
- docs/Modelagem/especificacao_suplementar.md
- Correção de Texto de alguns artefatos
> fix: Correção de artefatos

- docs/Modelagem/lexicos.md
> Corrigindo o lexico

- docs/Modelagem/cenarios.md
> Configurando os cenarios

- docs/Elicitacao/introspeccao.md
- docs/Modelagem/especificacao_suplementar.md
Fazendo correções de acordo com a entrega 3
> fix: Adicionando elementos e corrigindo outros

- docs/Modelagem/lexicos.md
- Ajustes levantados pelo professor na Entrega 3.
> Ajusta da Entrega 3 - léxicos

- docs/Elicitacao/introspeccao.md
Consertando Link em Histórico de versão
Correção de um link
> Fix: Correção de link

- docs/Modelagem/Agil/historia_usuario.md
- ajustei as histórias de usuário colocando a entrevista
> ajuste história de usuário

- docs/Modelagem/Agil/historia_usuario.md
- ajuste da história de usuário
> ajustes finais

- docs/Elicitacao/introspeccao.md
- docs/Modelagem/Agil/backlog.md
> criando Backlog

- docs/Planejamento/cronograma_realizado.md
- Atualizando cronograma realizado
> Atualizando cronograma realizado

- docs/Modelagem/Agil/backlog.md
- Corrigindo estruturação das tabelas
- Adicionando campo de validação
> Atualizando Backlog

- docs/Atas/Reuniao04.md
- mkdocs.yml
- Adição da ata referente a reunião 4
> Adicionando Ata

- docs/Verificacao/template.md
- mkdocs.yml
> create: template e paginacao verificacao

- docs/Verificacao/Grupo5/Entrega3/Entrega3.md
- verificacao cenarios e casos de usos
> verificacao cenarios e casos de usos

- docs/Modelagem/lexicos.md
> Pré-verificação léxicos

- docs/Verificacao/Grupo5/Entrega3/casos-de-uso.md
- docs/Verificacao/Grupo5/Entrega3/cenarios.md
- Verificação casos de uso e cenários.
> verificacao-etapa3

- docs/Verificacao/Grupo5/Entrega3/casos-de-uso.md
- docs/Verificacao/Grupo5/Entrega3/cenarios.md
- Add 4 perguntas verificação de padronização do artefato
> add 4 perguntas padroes

- docs/Verificacao/Grupo5/Entrega3/esp-suplementar.md
- docs/Verificacao/Grupo5/Entrega3/lexicos.md
- Esse PR possui a verificacao dos documetos de lexicos e especificacao suplementar do grupo 05
> Documentos de verificacao

- docs/Verificacao/Grupo5/Entrega4/backlog.md
- docs/Verificacao/Grupo5/Entrega4/historias.md
- Criação da verificação da  história de usuário e do backlog
> adição backlog e historia de usuário

- docs/Verificacao/Grupo5/Entrega1/Aplicativo_Selecionado.md
- docs/Verificacao/Grupo5/Entrega1/Atas.md
- docs/Verificacao/Grupo5/Entrega1/Cronograma_Planjeado.md
- docs/Verificacao/Grupo5/Entrega1/Cronograma_Realizado.md
- docs/Verificacao/Grupo5/Entrega1/Entrega1.md
- docs/Verificacao/Grupo5/Entrega1/Ferramentas.md
- docs/Verificacao/Grupo5/Entrega1/Metodologias.md
- docs/Verificacao/Grupo5/Entrega1/Rich_Picture.md
- docs/Verificacao/Grupo5/Entrega1/aplicativo-selecionado.md
- docs/Verificacao/Grupo5/Entrega1/cronograma-planejado.md
- docs/Verificacao/Grupo5/Entrega1/cronograma-realizado.md
- docs/Verificacao/Grupo5/Entrega1/ferramenta.md
- docs/Verificacao/Grupo5/Entrega1/metodologia.md
- mkdocs.yml
> Create: Criado os Artefatos

- mkdocs.yml
> ajuste mkdocs

- docs/Verificacao/Grupo5/Entrega2/elicitacao/planejamento-elicitacao.md
- mkdocs.yml
- Referência pros documentos NFR, backlog e história de usuário
- Correção gramatical do Planejamento da Entrega 1
> mkdocs: referências e gramática

- docs/Verificacao/Grupo5/Entrega4/historias.md
- mkdocs.yml
- Corrigido link para o planejamento nas histórias de usuário
- Colocado nfr em minúsculo no mkdocs
> Links entre os arquivos

- docs/Guia/Verificacao/0planejamento-geral.md
- docs/Guia/Verificacao/Entrega-Modelo/0planejamento.md
- docs/Guia/Verificacao/Entrega-Modelo/1artefato.md
- mkdocs.yml
> Corrigindo links da barra de navegacao

- docs/Verificacao/Caesb/0planejamento-geral.md
- docs/Verificacao/Caesb/Entrega1/0planejamento.md
- docs/Verificacao/Caesb/Entrega1/Aplicativo_Selecionado.md
- docs/Verificacao/Caesb/Entrega1/Ferramentas.md
- docs/Verificacao/Caesb/Entrega1/Metodologias.md
- docs/Verificacao/Caesb/Entrega2/0planejamento.md
- docs/Verificacao/Caesb/Entrega2/elicitacao/personas.md
- docs/Verificacao/Caesb/Entrega2/priorizacao/tls.md
- docs/Verificacao/Caesb/Entrega3/0planejamento.md
- docs/Verificacao/Caesb/Entrega4/0planejamento.md
> Adicionando planejamentos

- docs/Verificacao/Caesb/Entrega2/priorizacao/FTF.md
> correção ftf

- docs/Verificacao/Caesb/Entrega1/Cronograma_Planejado.md
- docs/Verificacao/Caesb/Entrega2/elicitacao/brainstorming.md
- docs/Verificacao/Caesb/Entrega2/elicitacao/entrevista.md
- docs/Verificacao/Caesb/Entrega2/elicitacao/glossario.md
- docs/Verificacao/Caesb/Entrega2/elicitacao/perfilUsuario.md
- docs/Verificacao/Caesb/Entrega2/priorizacao/FTF.md
- docs/Verificacao/Caesb/Entrega3/lexicos.md
- mkdocs.yml
> correções finais

- docs/javascripts/tablesort.js
- mkdocs.yml
- toc.follow 
Faz com que a barra lateral seja rolada automaticamente para que o menu da sessão ativa esteja sempre visível.
- navigation.instant 
Quando o carregamento instantâneo está ativado, os cliques em todos os links internos serão interceptados e despachados via XHR sem recarregar totalmente a página.
A página resultante é analisada e injetada e todos os manipuladores de eventos e componentes são religados automaticamente, ou seja, o Material for MkDocs agora se comporta como um aplicativo de página única.
- navigation.top 
Um botão voltar ao topo será mostrado quando o usuário rolar a página para baixo, para rolar para o topo da página novamente. Ele é renderizado centralizado e logo abaixo do cabeçalho.
- javascripts/tablesort.js 
Tabelas ordenáveis. Agora os dados das tabelas …
> Recursos adicionados ao MkDocs

- docs/Pos-rastreabilidade/backward_from.md
- mkdocs.yml
> Create: Criando Backward from

- docs/Pos-Rastreabilidade/ForwardFrom.md
- Link das imagens na GitPages
- correções gramaticais
> Imagens ForwardFrom.md

- docs/Planejamento/aplicativo_escolhido.md
- docs/Verificacao/Caesb/Entrega1/Aplicativo_Selecionado.md
- Atualização do artefato de Aplicativo Escolhido, de acordo com a checklist elaborada na etapa de verificação;
- Atualização do artefato de verificação após as correções realizadas.
> Correção Pós-verificação do Aplicativo Escolhido

- docs/EntregaFinal/entrega-final.md
- mkdocs.yml
- Criação e estruturação do documento de entrega final
> Criacao do documento de entrega final

- mkdocs.yml
- R em minúsculo em Rastreabilidade
> Correções MkDocs

- docs/EntregaFinal/entrega-final.md
- mkdocs.yml
- Ajuste rastreabilidade no mkdocs e criação da execução do projeto
> Execucao do projeto paulo
